<a href="https://colab.research.google.com/github/Yashu1231/Yashu1231/blob/main/InsurancePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving TravelInsurancePrediction (1).csv to TravelInsurancePrediction (1) (2).csv


In [ ]:
dataset=pd.read_csv("TravelInsurancePrediction (1) (2).csv")

In [ ]:
print(dataset)

      Age  AnnualIncome  FamilyMembers  ChronicDiseases  TravelInsurance
0      31        400000              6                1                0
1      31       1250000              7                0                0
2      34        500000              4                1                1
3      28        700000              3                1                0
4      28        700000              8                1                0
...   ...           ...            ...              ...              ...
1982   33       1500000              4                0                1
1983   28       1750000              5                1                0
1984   28       1150000              6                1                0
1985   34       1000000              6                0                1
1986   34        500000              4                0                0

[1987 rows x 5 columns]


In [ ]:
print(dataset.shape)
dataset.shape[0]

(1987, 5)


1987

In [ ]:
print(dataset.head(10)) ##first 10 tuples
print(dataset.tail(10)) ##last 10 tuples
dataset.shape ## prints number of rows and column

   Age  AnnualIncome  FamilyMembers  ChronicDiseases  TravelInsurance
0   31        400000              6                1                0
1   31       1250000              7                0                0
2   34        500000              4                1                1
3   28        700000              3                1                0
4   28        700000              8                1                0
5   25       1150000              4                0                0
6   31       1300000              4                0                0
7   31       1350000              3                0                1
8   28       1450000              6                1                1
9   33        800000              3                0                0
      Age  AnnualIncome  FamilyMembers  ChronicDiseases  TravelInsurance
1977   25       1350000              6                0                1
1978   34        700000              5                0                1
1979   28  

(1987, 5)

In [ ]:
x=dataset.iloc[:,:-1]  ### segregating dataset into x(independent variable or input) and y(dependent variable or output)
y=dataset.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
###now feature scalng will be done to make our data consistent(fit) with scale
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)
print(x_test)





[[ 1.82831616  0.0784586  -0.48260588 -0.61614092]
 [-0.56132514 -0.98550787  0.76471895 -0.61614092]
 [-0.21994781  0.47744603 -0.48260588  1.62300534]
 ...
 [-1.24407979 -1.11850367  0.14105653  1.62300534]
 [-0.21994781  0.74343764 -1.1062683  -0.61614092]
 [-1.58545712  0.61044183 -0.48260588 -0.61614092]]
[[ 1.48693883  1.54141249  0.14105653  1.62300534]
 [-0.56132514  0.74343764  1.38838137  1.62300534]
 [-0.21994781 -0.05453721 -1.1062683  -0.61614092]
 ...
 [ 0.46280685 -1.38449529  1.38838137  1.62300534]
 [ 0.46280685 -1.38449529  1.38838137 -0.61614092]
 [ 0.46280685  1.14242507  0.14105653 -0.61614092]]


In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)


LogisticRegression()

In [ ]:
y_pred=model.predict(x_test)
##print(np.concatenate(y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)))

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)

print(cm)

print("accuracy of the model is: {0}".format(accuracy_score(y_test,y_pred)*100))

[[276  52]
 [ 70  99]]
accuracy of the model is: 75.45271629778671
